apiVersion : apps/v1
kind: Deployment
metadata:
  name: okrnotification 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: okrnotification
  template:
    metadata:
      labels:
        app: okrnotification 
    spec:
      containers:
        - name: okrnotification 
          image: unlockokrregistrydev.azurecr.io/okrnotification
          ports:
          - containerPort: 80
          env:
          - name: "ASPNETCORE_ENVIRONMENT"
            value: "Development"
          - name: "ASPNETCORE_FORWARDEDHEADERS_ENABLED"
            value: "true"